/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package personel;

import personel.PersonelIslemleri;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author ushat
 */
public class PersonelEkranı extends javax.swing.JDialog {
    
    static DefaultTableModel model;
    PersonelIslemleri islemler=new PersonelIslemleri();
    PersonelIslemleri.Ekle ekle= new PersonelIslemleri().new Ekle();

    /**
     * Creates new form PersonelEkranı
     */
    public PersonelEkranı(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model=(DefaultTableModel)Personel_Tablosu.getModel();
        personelGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Txt_ara = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Txt_ad = new javax.swing.JTextField();
        Txt_soyad = new javax.swing.JTextField();
        Txt_departman = new javax.swing.JTextField();
        Txt_maas = new javax.swing.JTextField();
        Btn_personelGuncelle = new javax.swing.JButton();
        Btn_personelEkle = new javax.swing.JButton();
        Btn_sil = new javax.swing.JButton();
        Btn_temizle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Personel_Tablosu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        Lbl_mesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ara");

        Txt_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_araActionPerformed(evt);
            }
        });
        Txt_ara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_araKeyReleased(evt);
            }
        });

        jLabel2.setText("Ad");

        jLabel3.setText("Soyad");

        jLabel4.setText("Departman");

        jLabel5.setText("Maaş");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Txt_soyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_soyadActionPerformed(evt);
            }
        });

        Txt_maas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_maasActionPerformed(evt);
            }
        });

        Btn_personelGuncelle.setText("Personel Güncelle");
        Btn_personelGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_personelGuncelleActionPerformed(evt);
            }
        });

        Btn_personelEkle.setText("Personel Ekle");
        Btn_personelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_personelEkleActionPerformed(evt);
            }
        });

        Btn_sil.setText("Sil");
        Btn_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_silActionPerformed(evt);
            }
        });

        Btn_temizle.setText("Temizle");
        Btn_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_temizleActionPerformed(evt);
            }
        });

        Personel_Tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "ad", "soyad", "departman", "maaş"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Personel_Tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Personel_TablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Personel_Tablosu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(Btn_temizle))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txt_ad)
                                    .addComponent(Txt_soyad)
                                    .addComponent(Txt_departman)
                                    .addComponent(Txt_maas, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Lbl_mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_departman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_maas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_temizle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_personelGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_personelEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_mesaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
            
    private void Btn_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_silActionPerformed
        // TODO add your handling code here:
         Lbl_mesaj.setText("");
        int selectedrow = Personel_Tablosu.getSelectedRow();
        if (selectedrow == -1) {
        //tablodan silinecek eleman kontrolü
            if (model.getRowCount() == 0) {
            
                Lbl_mesaj.setText("Tablo Boş Silinecek Eleman Yok");
                
            }
            else {
            
                Lbl_mesaj.setText("Lütfen Silinecek Çalışanı Seçiniz! ");
                
            }
            
        }
        else {
        //seçili eleman varsa sil metodu çağrılıyor
        //tabloda seçili olan elemanın id sine göre işlem yapılıyor
            int id = (int)model.getValueAt(selectedrow, 0);
            islemler.personelSil(id);
            personelGoruntule();
            //Silme işleminden sonra tekrar personeller görüntüleniyor
            Lbl_mesaj.setText("Personel Başarıyla Silindi");
            
        }
    }//GEN-LAST:event_Btn_silActionPerformed

    private void Txt_soyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_soyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_soyadActionPerformed

    private void Txt_maasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_maasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_maasActionPerformed

    private void Txt_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_araActionPerformed

    private void Txt_araKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_araKeyReleased
        // TODO add your handling code here:
          String ara;
        ara  = Txt_ara.getText();
        islemler.Ara(ara);
    }//GEN-LAST:event_Txt_araKeyReleased

    private void Btn_personelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_personelEkleActionPerformed
        // TODO add your handling code here:
         Lbl_mesaj.setText("");
        if (Txt_ad.getText().equals("") || Txt_departman.getText().equals("")
                || Txt_soyad.getText().equals("") || Txt_maas.getText().equals("")){
        
            Lbl_mesaj.setText("Personel Eklenemedi Tüm Alanları Doldurunuz...");
            
        }
        else {
       
        String ad = Txt_ad.getText();
        String soyad = Txt_soyad.getText();
        String departman = Txt_departman.getText();
        String maas = Txt_maas.getText();
       
        ekle.personelEkle(ad, soyad, departman, maas);
       
        personelGoruntule();
      
        Lbl_mesaj.setText("Personel Eklendi...");
    }//GEN-LAST:event_Btn_personelEkleActionPerformed
    }
    private void Btn_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_temizleActionPerformed
        // TODO add your handling code here:
        Txt_ad.setText("");
        Txt_soyad.setText("");
        Txt_departman.setText("");
        Txt_maas.setText("");
        Lbl_mesaj.setText("");
        Personel_Tablosu.getSelectionModel().clearSelection();
    }//GEN-LAST:event_Btn_temizleActionPerformed

    private void Personel_TablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Personel_TablosuMouseClicked
        // TODO add your handling code here:
          int selectedrow = Personel_Tablosu.getSelectedRow();
        
        Txt_ad.setText(model.getValueAt(selectedrow, 1).toString());
        Txt_soyad.setText(model.getValueAt(selectedrow, 2).toString());
        Txt_departman.setText(model.getValueAt(selectedrow, 3).toString());
        Txt_maas.setText(model.getValueAt(selectedrow, 4).toString());
    }//GEN-LAST:event_Personel_TablosuMouseClicked

    private void Btn_personelGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_personelGuncelleActionPerformed
        // TODO add your handling code here:
          String ad = Txt_ad.getText();
        String soyad = Txt_soyad.getText();
        String departman = Txt_departman.getText();
        String maas = Txt_maas.getText();
         int selectedrow = Personel_Tablosu.getSelectedRow();
         //Personel tablosunda seçili eleman kontrolü yapılıyor
         if (selectedrow == -1) {
         
             if (model.getRowCount() == 0) {
             
                 Lbl_mesaj.setText("Tablo Boş Seçilecek ELeman Yok!");
             
             }
             else {
             
                 Lbl_mesaj.setText("Lütfen Güncellenecek Personeli Seçiniz");
                 
             }
           
         }
         else {
         
             if (Txt_ad.getText().equals("") || Txt_departman.getText().equals("")
                || Txt_soyad.getText().equals("") || Txt_maas.getText().equals("")){
        //Güncellenecek elemanın tüm verilerinin doldurulup doldurulmadığı kontrol ediliyor
            Lbl_mesaj.setText("Personel Güncellenemedi Tüm Alanları Doldurunuz...");
            
        }
        else{
             int id = (int)model.getValueAt(selectedrow, 0 );
             islemler.personelGuncelle(id,ad,soyad,departman,maas);
             //Text alanlarında eksik yoksa güncelleme metodu çağrılıyor
             personelGoruntule();
             Lbl_mesaj.setText("Personel Güncellendi.");
        }
         }
    }//GEN-LAST:event_Btn_personelGuncelleActionPerformed
 
    
        
        
        
    
    /**
     * @param args the command line arguments
     */
     public void personelGoruntule(){
    
        model.setRowCount(0);
        ArrayList<Personel> calisanlar = new ArrayList<Personel>();
        calisanlar = islemler.personelGetir();
        //personel getir metoduyla personeller çekiliyor
        if(calisanlar != null) {
        
            for (Personel calisan : calisanlar){
                
              
                Object[] eklenecek = {calisan.getId(), calisan.getAd(), calisan.getSoyad(), calisan.getDepartman(), calisan.getMaas()};
                model.addRow(eklenecek);
            }
        }
        
    } 
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PersonelEkranı dialog = new PersonelEkranı(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_personelEkle;
    private javax.swing.JButton Btn_personelGuncelle;
    private javax.swing.JButton Btn_sil;
    private javax.swing.JButton Btn_temizle;
    private javax.swing.JLabel Lbl_mesaj;
    public static javax.swing.JTable Personel_Tablosu;
    private javax.swing.JTextField Txt_ad;
    private javax.swing.JTextField Txt_ara;
    private javax.swing.JTextField Txt_departman;
    private javax.swing.JTextField Txt_maas;
    private javax.swing.JTextField Txt_soyad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
