/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package stok;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ushat
 */
public class StokEkran extends javax.swing.JDialog {

    /**
     * Creates new form StokEkran
     */
    static DefaultTableModel  model1;
    MalzemeIslemleri stokislem = new MalzemeIslemleri();
    
    MalzemeIslemleri.Sil sil = new MalzemeIslemleri().new Sil();
    
    
    
    public StokEkran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         model1 = (DefaultTableModel)Malzeme_tablosu.getModel();
        malzemeGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_stokAra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Txt_isim = new javax.swing.JTextField();
        Txt_barkod = new javax.swing.JTextField();
        Txt_tur = new javax.swing.JTextField();
        Txt_miktar = new javax.swing.JTextField();
        Txt_fiyat = new javax.swing.JTextField();
        Txt_kayitTarihi = new javax.swing.JTextField();
        Btn_tarih = new javax.swing.JButton();
        Btn_malzemeEkle = new javax.swing.JButton();
        Btn_malzemeGuncelle = new javax.swing.JButton();
        Btn_malzemeSil = new javax.swing.JButton();
        Btn_sifirla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Malzeme_tablosu = new javax.swing.JTable();
        Lbl_stokmesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Ara");

        Txt_stokAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_stokAraActionPerformed(evt);
            }
        });
        Txt_stokAra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_stokAraKeyReleased(evt);
            }
        });

        jLabel2.setText("Barkod");

        jLabel3.setText("İsim");

        jLabel4.setText("Tür");

        jLabel5.setText("Miktar");

        jLabel6.setText("Fiyat");

        jLabel7.setText("Kayıt Tarihi");

        Txt_isim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_isimActionPerformed(evt);
            }
        });

        Btn_tarih.setText("Tarih");
        Btn_tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_tarihActionPerformed(evt);
            }
        });

        Btn_malzemeEkle.setText("Malzeme Ekle");
        Btn_malzemeEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_malzemeEkleActionPerformed(evt);
            }
        });

        Btn_malzemeGuncelle.setText("Malzeme Güncelle");
        Btn_malzemeGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_malzemeGuncelleActionPerformed(evt);
            }
        });

        Btn_malzemeSil.setText("Malzeme Sil");
        Btn_malzemeSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_malzemeSilActionPerformed(evt);
            }
        });

        Btn_sifirla.setText("Sıfırla");
        Btn_sifirla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_sifirlaActionPerformed(evt);
            }
        });

        Malzeme_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "isim", "barkod", "tur", "miktar", "fiyat", "kayittarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Malzeme_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Malzeme_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Malzeme_tablosu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_tarih)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_stokAra)
                                    .addComponent(Txt_isim)
                                    .addComponent(Txt_tur)
                                    .addComponent(Txt_miktar)
                                    .addComponent(Txt_fiyat)
                                    .addComponent(Txt_kayitTarihi)
                                    .addComponent(Txt_barkod))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Btn_malzemeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(Btn_malzemeEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_sifirla, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                                .addComponent(Btn_malzemeGuncelle)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_stokmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_stokAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_isim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_tur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_kayitTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_tarih)
                .addGap(14, 14, 14)
                .addComponent(Lbl_stokmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_malzemeGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_malzemeEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_malzemeSil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_sifirla, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_stokAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_stokAraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_stokAraActionPerformed

    private void Txt_isimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_isimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_isimActionPerformed

    private void Btn_tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_tarihActionPerformed
        // TODO add your handling code here:
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        Txt_kayitTarihi.setText(dateFormat.format(cal.getTime()));
    }//GEN-LAST:event_Btn_tarihActionPerformed

    private void Btn_malzemeEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_malzemeEkleActionPerformed
        // TODO add your handling code here:
          Lbl_stokmesaj.setText("");
        if (Txt_isim.getText().equals("") || Txt_barkod.getText().equals("") || Txt_tur.getText().equals("")
                || Txt_miktar.getText().equals("") || Txt_fiyat.getText().equals("") || Txt_kayitTarihi.getText().equals("")){
        //Eklenecek malzemeye ait tüm bilgilerin eksiksiz olması kontrol ediliyor
            Lbl_stokmesaj.setText("Malzeme Eklenemedi Tüm Alanları Doldurunuz...");
            
        }
        else {
        //Bilgiler eksiksiz ise verileri çekilip
        //Malzeme işlemleri sınıdında malzemeEkle metoduna 
        //gönderilip veritabanına ekleniyor
        String isim = Txt_isim.getText();
        String barkod = Txt_barkod.getText();
        String tur = Txt_tur.getText();
        String miktar = Txt_miktar.getText();
        String fiyat = Txt_fiyat.getText();
        String kayittarihi = Txt_kayitTarihi.getText();
        
        stokislem.malzemeEkle(isim, barkod, tur, miktar, fiyat, kayittarihi);
        //malzeme ekleme sonrası veri tabanı tekrar görüntüleniyor
        malzemeGoruntule();
        Lbl_stokmesaj.setText("MalzemeEklendi...");
         
            
        }
        
    }//GEN-LAST:event_Btn_malzemeEkleActionPerformed

    private void Txt_stokAraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_stokAraKeyReleased
        // TODO add your handling code here:
          String stokAra;
        stokAra  = Txt_stokAra.getText();
        
        stokislem.dinamikAra(stokAra);
    }//GEN-LAST:event_Txt_stokAraKeyReleased

    private void Btn_malzemeGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_malzemeGuncelleActionPerformed
        // TODO add your handling code here:
        String ad = Txt_isim.getText();
        String barkod = Txt_barkod.getText();
        String tur = Txt_tur.getText();
        String miktar = Txt_miktar.getText();
        String fiyat = Txt_fiyat.getText();
        String kayittarihi = Txt_kayitTarihi.getText();
        
         int selectedrow = Malzeme_tablosu.getSelectedRow();
         if (selectedrow == -1) {
         
             if (model1.getRowCount() == 0) {
             
                 Lbl_stokmesaj.setText("Tablo Boş Seçilecek ELeman Yok!");
            
             
             }
             else {
             
                 Lbl_stokmesaj.setText("Lütfen Güncellenecek Malzemeyi Seçiniz");
                 
             }
           
         }
         else {
         
             if (Txt_isim.getText().equals("") || Txt_barkod.getText().equals("") || Txt_tur.getText().equals("")
                || Txt_miktar.getText().equals("")  || Txt_fiyat.getText().equals("") || Txt_kayitTarihi.getText().equals("")){
       
            Lbl_stokmesaj.setText("Malzeme Eklenemedi Tüm Alanları Doldurunuz...");
            
        }
        else{
                 
             int id = (int)model1.getValueAt(selectedrow, 0 );
             stokislem.malzemeGuncelle(id, ad, barkod, tur, miktar, fiyat, kayittarihi);
             
             malzemeGoruntule();
             
             Lbl_stokmesaj.setText("Stok Güncellendi.");
        }
         }
        
    }//GEN-LAST:event_Btn_malzemeGuncelleActionPerformed

    private void Malzeme_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Malzeme_tablosuMouseClicked
        // TODO add your handling code here:
         int selectedrow = Malzeme_tablosu.getSelectedRow();
        
        Txt_isim.setText(model1.getValueAt(selectedrow, 1).toString());
        Txt_barkod.setText(model1.getValueAt(selectedrow, 2).toString());
        Txt_tur.setText(model1.getValueAt(selectedrow, 3).toString());
        Txt_miktar.setText(model1.getValueAt(selectedrow, 4).toString());
        Txt_fiyat.setText(model1.getValueAt(selectedrow, 5).toString());
        Txt_kayitTarihi.setText(model1.getValueAt(selectedrow, 6).toString());
    }//GEN-LAST:event_Malzeme_tablosuMouseClicked

    private void Btn_malzemeSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_malzemeSilActionPerformed
        // TODO add your handling code here:
         Lbl_stokmesaj.setText("");
        int selectedrow = Malzeme_tablosu.getSelectedRow();
        //tablodan silinecek eleman seçiliyor
        if (selectedrow == -1) {
            if (model1.getRowCount() == 0) {
                Lbl_stokmesaj.setText("Tablo Boş Silinecek Malzeme Yok");
                //tabloda seçilecek eleman yoksa uyarı veriyor
            } else {
                Lbl_stokmesaj.setText("Lütfen Silinecek Malzemeyi Seçiniz! ");  
                //tabloda seçili eleman yoksa uyarı veriyor
            }
        }
        else {
            int id = (int)model1.getValueAt(selectedrow, 0);
            sil.malzemeSil(id);
            //Inner Class tan olşan sil objesinden malzemeSil metodu çağrılıyor
            malzemeGoruntule();
            Lbl_stokmesaj.setText("Malzeme Silme İşlemi Gerçekleşti");
        }
    }//GEN-LAST:event_Btn_malzemeSilActionPerformed

    private void Btn_sifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_sifirlaActionPerformed
        // TODO add your handling code here:
         Txt_isim.setText("");
        Txt_barkod.setText("");
        Txt_tur.setText("");
        Txt_miktar.setText("");
        Txt_fiyat.setText("");
        Txt_kayitTarihi.setText("");
        Lbl_stokmesaj.setText("");
        Malzeme_tablosu.getSelectionModel().clearSelection();
    }//GEN-LAST:event_Btn_sifirlaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public void malzemeGoruntule(){
    //malzeme görüntüleme metodu
        model1.setRowCount(0);
        ArrayList<Malzeme> malzemeler = new ArrayList<Malzeme>();
        malzemeler = stokislem.malzemeGetir();
        if(malzemeler != null) {
        
            for (Malzeme malzeme : malzemeler){
                //private tanımlı değişkene erişim 
                Object[] eklenecek = {malzeme.getId(), malzeme.getIsim(), malzeme.getBarkod(), malzeme.getTur(), malzeme.getMiktar(), malzeme.getFiyat(), malzeme.getKayittarihi()};
                model1.addRow(eklenecek);
            }
        }
        
    } 

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StokEkran dialog = new StokEkran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_malzemeEkle;
    private javax.swing.JButton Btn_malzemeGuncelle;
    private javax.swing.JButton Btn_malzemeSil;
    private javax.swing.JButton Btn_sifirla;
    private javax.swing.JButton Btn_tarih;
    private javax.swing.JLabel Lbl_stokmesaj;
    public static javax.swing.JTable Malzeme_tablosu;
    private javax.swing.JTextField Txt_barkod;
    private javax.swing.JTextField Txt_fiyat;
    private javax.swing.JTextField Txt_isim;
    private javax.swing.JTextField Txt_kayitTarihi;
    private javax.swing.JTextField Txt_miktar;
    private javax.swing.JTextField Txt_stokAra;
    private javax.swing.JTextField Txt_tur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
